### ISSUE TITLE
panic: parsing private key: ssh: cannot decode encrypted private keys

### ISSUE THREAD

**Issue by jdub** [glassechidna/ec2connect#1]
Looks like this needs additional work to support encrypted private keys? Seems like a lot of other projects that have hit this issue.

The error string comes from [`x/crypto/ssh`](https://go.googlesource.com/crypto/+/refs/heads/master/ssh/keys.go#878), probably provoked by the `ParsePrivateKey` call in [`NormalizeKey`](https://github.com/glassechidna/ec2connect/blob/master/pkg/ec2connect/authorize.go#L61).

**Comment by jdub** [comment]
Ah, I see you're parsing the private key to get the public key. If you allow users to pass the public key file instead, you can remove this problem and avoid a bunch of security scrutiny.

**Comment by aidansteele** [comment]
Thanks for the feedback! In my rush to get this out, I forgot to address this. 

What do you think is the appropriate way to handle this? I’m thinking that during `setup`:

* If a path is passed in, use that - otherwise use ~/.ssh/id_rsa.pub. If it doesn’t exist, try the private key
* if it’s a pub key, use that and stop here. 
* If it’s a priv key, attempt to generate and save the pub key to disk
* if it fails, ask the user to provide a passphrase to decrypt the priv key and then save the pub key to disk

Should I support ssh-agent too?

**Comment by jdub** [comment]
If you only support public keys (which is all you need for the AWS API), then you can dodge all of that complexity and any security concerns, and leave it to the (more trusted) SSH client.

(Are there cases I'm unfamiliar with where users only have private key files?)

**Comment by aidansteele** [comment]
Good points. I'm not sure how it happened, but somehow one of my laptops was missing an `id_rsa.pub` and one out of three people I asked had the same on their laptops. 

I've since changed the behaviour and released 0.0.3 - let me know if that fixes it for you.

**Comment by jdub** [comment]
Nice, thanks! 😙👌🏻
